version: '3.7'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      retries: 20
      interval: 5s

  spring-boot-app:
    container_name: product-demo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
